### ISSUE TITLE
Failed to load web3, accounts, or contract. Check console for details.

### ISSUE THREAD

**Issue by arnaveenkumar** [joshma91/openlaw-dapp-tutorial#1]
Hi,

I followed this tutorial. When I tried to run the app, it throws this error "Failed to load web3, accounts, or contract. Check console for details.". 

Prior to this error, I am getting this error message in the browser "Unhandled Rejection (SecurityError): The operation is insecure."

function unregister() {
 if ('serviceWorker' in navigator) {
navigator.serviceWorker.ready.then(function (registration) {
 registration.unregister();
  });
   }

I am running this on Windows 10/FireFox. 

Any help is appreciated in resolving this issue.

**Comment by Flora258** [comment]
Getting the same error, for a react app. Has anyone found a solution?
